%% Preload script for the Graz_bci_basic %%
% Called by model call back functions "InitFcn"

% Define global storage variable
global BCI;
%global fig;
%fig.fig = figure();

hand = imread('hand.png');
foot = imread('foot2.png');
cross = imread('cross2.png');
%global fig;
%fig.fig = figure();

hFig = figure(...
    'Visible','on',...
    'Color', 'k',...    
    'ToolBar','None',...
    'Menu','None',...
    'Units','normalized',...
    'Position',[0 0 1 1]);

%imshow(BCI.black);

%imshow(BCI.black);
set(hFig, 'Units', 'Pixel');
pos = get(hFig, 'Position');

crossPanel = uipanel(...
    'Parent', hFig,...
    'Units','Pixel',...
    'Position',[floor(pos(3)/2)-400 + pos(2), floor(pos(4)/2)-400 + pos(1), 800, 800],...
    'BackgroundColor','k',...
    'BorderType','none',...
    'tag', 'crossPanel',...
    'Visible','off');

crossAx = axes(...
    'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'Parent', crossPanel,...
    'Color','k',...
    'XTick', [],...
    'YTick', [],...
    'XTickLabel', [],...
    'YTickLabel', []);

imshow(cross, 'Parent', crossAx);
% -------------------------------------------------------------
% axis where the image of the foot is presented

footPanel = uipanel(...
    'Parent', hFig,...
    'Units','Pixel',...
    'Position',[floor(pos(3)/2)-150 + pos(2), floor(pos(4)/2)-150 + pos(1), 300, 300],...
    'BackgroundColor','k',...
    'BorderType','none',...
    'tag','footPanel',...
    'Visible','off');

footAx = axes(...
    'Parent', footPanel,...
    'Units','normalized',...
    'Position',[0 0 1 1],...
    'Color','k',...
    'XTick', [],...
    'YTick', [],...
    'XTickLabel', [],...
    'YTickLabel', []);

imshow(foot,'Parent',footAx);
% hand panel
% ---------------------------------------------------------------
handPanel = uipanel(...
    'Parent', hFig,...
    'Units','Pixel',...
    'Position',[floor(pos(3)/2)-150 + pos(2), floor(pos(4)/2)-150 + pos(1), 300, 300],...
    'BackgroundColor','k',...
    'BorderType','none',...
    'tag', 'handPanel',...
    'Visible','off');

% axis showing the image of the hand
handAx = axes(...
    'Parent', handPanel,...
    'Units','normalized',...
    'Position',[0 0 1 1],...
    'Color','k',...
    'XTick', [],...
    'YTick', [],...
    'XTickLabel', [],...
    'tag','handAx',...
    'YTickLabel', []);

imshow(hand, 'Parent', handAx);

% feedback panel


%BCI.hFig = figure(...
    %'Units', 'normalized',...
    %'Position', [0, 0, 1, 1]);
%imshow(cross);



% Initialization parameters
%set_param(bdroot, 'SolverName', 'FixedStepDiscrete');

set_param(bdroot, 'SolverName', 'FixedStep');
%set_param('graz_bci_model','StartFcn','localAddEventListener');
set_param(bdroot, 'FixedStep', [ num2str(1) '/' num2str(BCI.SampleRate)])