% opening the simulink model

%clear
global handles;

handles.fig = figure(...
    'Visible', 'on',...
    'Units', 'normalized',...
    'Position', [0.4 0.4 0.2 0.4],...
    'Name', 'NIBCI2', ...
    'Tag', 'fig',...
    'Color', 'white',...
    'Toolbar', 'none', ...
    'MenuBar', 'none');

handles.fig2 = figure(...
    'Units','normalized',...
    'OuterPosition',[0.3, 0, 0.7, 1],...
    'Visible','off'); 

handles.fig3 = figure(...
    'Units','normalized',...
    'OuterPosition',[0.65, 0, 0.35, 1],...
    'Visible','off',...
    'Color', 'white',...
    'Toolbar', 'none', ...
    'MenuBar', 'none'); 

handles.fig4 = figure(...
    'Units','normalized',...
    'OuterPosition',[0.3, 0, 0.35, 1],...
    'Visible','off',...
    'Color', 'white',...
    'Toolbar', 'none', ...
    'MenuBar', 'none'); 

handles.background = uipanel(...
    'Title','',...
    'Parent', handles.fig,...
    'Units', 'normalized',...
    'Position',[0 0 1 0.8],...
    'BackgroundColor', 'white',...
    'Visible', 'on');

handles.startButton = uicontrol(...
    'Parent', handles.background,...
    'Units','normalized',...
    'FontUnits', 'normalized',...
    'Position', [0.1 0.05 0.8 0.15],...
    'Style', 'Pushbutton', ...
    'FontSize', 0.3,...
    'String', 'Start',...
    'Callback', @start_Callback);

% PSD axes
%-----------------------------------------------------

handles.erpC3 = axes(...
            'Parent', handles.fig4, ...
            'Color', 'white',...
            'Position', [0.05 0.05 0.95 0.25]);

handles.erpCz = axes(...
            'Parent', handles.fig4, ...
            'Color', 'white',...
            'Position', [0.05 0.35 0.95 0.25]);

handles.erpC4 = axes(...
            'Parent', handles.fig4, ...
            'Color', 'white',...
            'Position', [0.05 0.65 0.95 0.25]);
        
% ERDS axes
%-----------------------------------------------------

handles.pdsC3 = axes(...
            'Parent', handles.fig3, ...
            'Color', 'white',...
            'Position', [0.05 0.05 0.95 0.25]);

handles.pdsCz = axes(...
            'Parent', handles.fig3, ...
            'Color', 'white',...
            'Position', [0.05 0.35 0.95 0.25]);

handles.pdsC4 = axes(...
            'Parent', handles.fig3, ...
            'Color', 'white',...
            'Position', [0.05 0.65 0.95 0.25]);
        
        
% Post Processing Panel 
%-----------------------------------------------------
% panel housing all elements of post processing
handles.dataScreen = uipanel(...
    'Title', '',...,
    'Parent', handles.fig,...
    'Units', 'normalized',...
    'Position', [0 0 1 1],...
    'BackgroundColor', 'white',...
    'Visible', 'off');

handles.loadDataButton = uicontrol(...
      'Parent', handles.dataScreen,...
      'Units', 'normalized',...
     'FontUnits','normalized',...
     'Position',[0.05, 0.85, 0.5, 0.1] ,...
     'FontSize', 0.3,...
     'String', 'Load Data',...
     'Callback', @loadData_Callback);
 
 handles.eegButton = uicontrol(...
     'Parent', handles.dataScreen,...
     'Units', 'normalized',...
     'FontUnits','normalized',...
     'Position', [0.05, 0.65, 0.5, 0.1],...
     'FontSize', 0.3,...
     'String', 'EEG',...
     'Callback', @eegButton_Callback);
 
 handles.PDSButton = uicontrol(...
     'Parent', handles.dataScreen,...
     'Units', 'normalized',...
     'FontUnits','normalized',...
     'Position', [0.05, 0.45, 0.5, 0.1],...
     'FontSize', 0.3,...
     'String', 'PSD',...
     'Callback', @PDS_Callback);
 
 handles.ERDSButton = uicontrol(...
     'Parent', handles.dataScreen,...
     'Units', 'normalized',...
     'FontUnits','normalized',...
     'Position', [0.05, 0.25, 0.5, 0.1],...
     'FontSize', 0.3,...
     'String', 'ERDS',...
     'Callback', @ERDS_Callback);
 
 
 handles.ERPButton = uicontrol(...
     'Parent', handles.dataScreen,...
     'Units', 'normalized',...
     'FontUnits','normalized',...
     'Position', [0.05, 0.05, 0.5, 0.1],...
     'FontSize', 0.3,...
     'String', 'ERP',...
     'Callback', @ERP_Callback);
%handles.eegPlot = uipanel(...
%    'Title','',...
%    'Parent', handles.dataScreen,...
%    'Units', 'normalized',...
%    'Position',[0.05 0.05 0.60 0.45],...
%    'BackgroundColor', 'white',...
%    'Visible', 'off');
%        

%handles.defaultButton = uicontrol(...
%    'Parent', handles.background,...
%    'Units','normalized',...
%    'FontUnits', 'normalized',...
%    'Position', [0.5 0.18 0.4 0.1],...
%    'Style', 'Pushbutton', ...
%    'FontSize', 0.5,...
%    'String', 'Default',...
%    'Callback', @default_Callback);

% handles.psd = axes(...
%             'Parent', handles.dataScreen, ...
%             'Color', 'white',...
%             'Position', [0.7 0.05 0.25 0.45]);

% Descriptions
%---------------------------------------------------------
handles.nTrialsText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.85 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'nTrials:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.preRunTrials = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.75 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'Pre Run Time:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.preCueText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.65 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'Pre Cue:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.cueText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.55 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'Cue:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.miText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.45 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'MI:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.breakText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.35 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'Break:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

handles.postRunText = uicontrol(...
    'Parent', handles.background,...
    'Style', 'Text',...
    'Units','normalized', ...
    'Position', [0.1 0.25 0.4 0.1], ...
    'FontUnits', 'normalized',...
    'HorizontalAlignment', 'left',...
    'String', 'Post Run:',...
    'FontSize', 0.6, ...
    'BackgroundColor', 'white');

% Text fields
%---------------------------------------------------------

% Name edit field
handles.trialsEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String','30',...
    'Units','normalized',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Position', [0.5 0.87 0.4 0.08]);

handles.preRunEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String','5',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.77 0.4 0.08]);

handles.preCueEdit = uicontrol(...
    'Parent', handles.background, ...
    'String', '2',...
    'Style','Edit',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.67 0.4 0.08]);

handles.cueEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String','1',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.57 0.4 0.08]);

handles.miEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String','5',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.47 0.4 0.08]);

handles.breakEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String','2',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.37 0.4 0.08]);

handles.postRunEdit = uicontrol(...
    'Parent', handles.background, ...
    'Style','Edit',...
    'String', '5',...
    'FontUnits', 'normalized',...
    'FontSize',0.7,...
    'Units','normalized',...
    'Position', [0.5 0.27 0.4 0.08]);

guidata(handles.fig, handles);
